---
# Lab Activity 2 - Daemonsets
# Deploy a Daemonset that leverages the nginx image
# Verify the daemonset has been created successfully
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx-ds
spec:
  selector:
    matchLabels:
      app: nginx-ds
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: nginx
        image: nginx
---
