---
# Deploy two pods:
# One pod with a label of “Tier = Web”
# One pod with a label of “Tier = App”
# Use any container image you see fit.
# Verify the labels are applied.
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    Tier: App
spec:
  containers:
  - name: busybox
    image: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    Tier: Web
spec:
  containers:
  - name: nginx
    image: nginx
---
