# Lab Activity 7 - Know how to configure the Kubernetes Scheduler
# Configure the Kube-Scheduler by adding --logtostderr=true to
# the existing configuration.
## sudo vim /etc/systemd/system/kube-scheduler.service
## sudo systemctl daemon-reload
## sudo systemctl restart  kube-scheduler.service
