apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-hostpath-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath
