---
# Lab Activity 3 - Application Monitoring
# Run the following:
# kubectl apply -f https://raw.githubusercontent.com/David-VTUK/CKAExampleYaml/master/nginx-svc-and-deployment.yaml
# Gather the events from a given pod from this deployment
# Gather the events from the replicaset created from this deployment
# Gather the events from the service from this deployment
# Acquire the list of endpoints associated with this service
# How are the endpoints determined?
# Which kubectl command would display all the logs from the pods created from this deployment?
