---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /datafiles/nfs/elasticsearch
    server: nfs.server
  persistentVolumeReclaimPolicy: Retain
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-volume-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /datafiles/nfs/elasticsearch-2
    server: nfs.server
  persistentVolumeReclaimPolicy: Retain
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-volume-3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /datafiles/nfs/elasticsearch-3
    server: nfs.server
  persistentVolumeReclaimPolicy: Retain
status: {}
