apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-server-ext
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
    nodePort: 30090
  selector:
    app: prometheus
    component: server
    release: prometheus
  type: NodePort
