apiVersion: v1
kind: Service
metadata:
  name: percona-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: cluster1
    app.kubernetes.io/name: percona-xtradb-cluster
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30036
