apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-pv
spec:
  containers:
  - name: mysql-pv
    image: mysql:8.0.18
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-volume
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pablow
  volumes:
  - name: mysql-volume
    persistentVolumeClaim:
      claimName: mysql-pvc
  
